import '@/styles/globals.css'
import type { Metadata } from 'next'
import type { FC, ReactNode } from 'react'
import { Header } from '@/components/header'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Untitled UI',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: ReactNode
}
const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="pt-BR">
      <body
        suppressHydrationWarning
        className={` ${inter.className} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
